Sound volume adjustment
WSUCEG-7140/Tempus_Fugit_Minecraft pull request #101
Opened 2023-07-25 17:55 UTC by xieWright

Added a volume bar that adjusts the volume of sound in the game. Added Doxygen comments and tests accordingly.

2023-07-25 19:09 UTC, Lurk390 requested changes
Main things is I don't really like how the slider looks (straight line would be cleaner imo) and some documentation changes.

2023-07-25 19:09 UTC, Lurk390 commented on assets/volume_slider.png
I'm not really a fan of this graphic, I think a simple horizontal line would suffice and is intuitive.

2023-07-25 19:09 UTC, Lurk390 commented on tempus_fugit_minecraft/sound.py
> +        '''!Initializes the class Sound. If a file path is named, uses that to load the sound file
Keep the `"""!` on its own line for readability

2023-07-25 19:09 UTC, Lurk390 commented on tempus_fugit_minecraft/sound.py
> +        '''!Loads the sound into the media player
Keep the """! on its own line for readability

2023-07-25 19:09 UTC, Lurk390 commented on tempus_fugit_minecraft/sound.py
> +        '''!Plays the sound file contained in the class
Keep the """! on its own line for readability

2023-07-25 19:09 UTC, Lurk390 commented on tempus_fugit_minecraft/sound.py
> +        '''!Initializes the class BackgroundSound. This is to separate sounds that will loop and have different
Keep the """! on its own line for readability

2023-07-25 19:09 UTC, Lurk390 commented on tempus_fugit_minecraft/sound_list.py
>  """
This should be at the top of the file above the imports

2023-07-25 19:09 UTC, Lurk390 commented on tempus_fugit_minecraft/sound_list.py
> +class SoundList():
Need a class docstring here

2023-07-25 19:09 UTC, Lurk390 commented on tempus_fugit_minecraft/window.py
> +        """Solves issue #"""
This comment looks incomplete, I'd either get rid of it or if you finish it use a normal comment with a `#`

2023-07-26 01:23 UTC, xieWright commented on assets/volume_slider.png
It probably would work too. Honestly speaking, I'm not much of an artist and trying to do the actual painting in pyglet is rough. The image itself is pretty replaceable.

2023-07-27 22:12 UTC, w1158mxs approved these changes
Small change - looks good! Thank you

2023-07-27 22:12 UTC, w1158mxs commented on tempus_fugit_minecraft/shaders.py
> +        @see [Issue#18](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/18)
issue #18 contain 
Creation of Sun object
Creation of Moon object
I suggest editing that while will not do it

2023-07-27 22:12 UTC, w1158mxs commented on tempus_fugit_minecraft/window.py
> +                                           x=WINDOW_WIDTH // 16,
Can you keep space between (x and =)
 x = WINDOW_WIDTH

2023-07-27 22:12 UTC, w1158mxs commented on tempus_fugit_minecraft/window.py
> +                                           x=WINDOW_WIDTH // 16,
same for y

2023-07-28 00:20 UTC, bakursait2 approved these changes
All looks good to me.

2023-07-28 03:00 UTC, criticalglitch approved these changes

2023-07-28 17:22 UTC, merged