Speed up
WSUCEG-7140/Tempus_Fugit_Minecraft pull request #43
Opened 2023-06-21 23:28 UTC by w1158mxs

- Add the speed-up function and its tests
- Organized code by moving global variables inside the Window class
- Organized cloud tests by moving functions inside their own class

2023-06-22 06:06 UTC, Lurk390 approved these changes
Putting the global variables and the tests within their own class is a big improvement to the code. Make sure to continue to make the variables uppercase if they are constants or lowercase if they are modified.

2023-06-22 18:18 UTC, criticalglitch approved these changes
Everything looks good, the code is well formatted and the variables are now instanced.

2023-06-22 18:28 UTC, bakursait2 approved these changes
Tests file is well formatted and organized. Putting all related tests in the same class is a good point to start from.

2023-06-22 18:39 UTC, xieWright requested changes
In regards to the variable names, the variable d should be distance. Other thing is that I think another issue is popping up in regards to global variables. Gonna need to discuss this with the team.

2023-06-22 22:00 UTC, Lurk390 commented on tests/test_minecraft.py
> +from tempus_fugit_minecraft.main import LIGHT_CLOUD
combine these lines together

2023-06-22 22:10 UTC, w1158mxs commented
> In regards to the variable names, the variable d should be distance. Other thing is that I think another issue is popping up in regards to global variables. Gonna need to discuss this with the team.

Can you mention which line has variable d, please? I didn't use variable d in my code

2023-06-22 23:36 UTC, xieWright approved these changes

2023-06-23 00:38 UTC, w1158mxs commented
contain speed up and organize variables in class in main, and class cloud test

2023-06-23 00:38 UTC, merged

2023-07-27 00:01 UTC, w1158mxs commented
Test pass
![speed_up_test_screenshot](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/assets/133145869/d7571fe0-e1dc-4d83-9e46-f90d1a239b62)