Improve Tests and Documentation
WSUCEG-7140/Tempus_Fugit_Minecraft pull request #53
Opened 2023-06-24 07:38 UTC by Lurk390

Fixes issues #48, #49, #50, #51 

Improved testing by simplifying files and using pyfixtures for performance. Also improved documentation:

1. Testing
    - Combined `test_minecraft.py` into `test_main.py`.
    - Added pytest fixtures at the class scope to remove redundant code and improve testing performance.

2. Documentation
    - Standardized docstrings format by removing unnecessary new lines and spaces and adding parameters and returns when appropriate.
    - Added class docstrings.
    - Included type hints for every function to improve code readability.

2023-06-25 21:10 UTC, xieWright requested changes
Currently, not too sure if this is an improvement to the current testing method. Would like to see a demonstration and have a vote on it Wed.

2023-06-26 20:21 UTC, w1158mxs approved these changes
good Job! Just import dark_clouds also

2023-06-26 20:21 UTC, w1158mxs commented on tempus_fugit_minecraft/main.py
what is the goal of specifying variables x,y,z, and n as float type? is that better for memory?

2023-06-26 20:21 UTC, w1158mxs commented on tests/test_main.py
you need to import dark_cloud also

2023-06-26 20:21 UTC, w1158mxs commented on tests/test_minecraft.py
I see you merge tests in 1 file, Good one!

2023-06-27 16:19 UTC, bakursait2 commented on tests/test_main.py
> +    yield Model()
this actually very helpful as we won't bother creating instances of Window and Model classes on each method.
Good job on this.

2023-06-27 23:12 UTC, Lurk390 commented on tests/test_main.py
This depends on who merges first, and the other person will have to fix the merge conflicts.

2023-06-27 23:12 UTC, Lurk390 commented on tempus_fugit_minecraft/main.py
It needs to be a float to support decimal numbers.

2023-06-28 02:27 UTC, xieWright approved these changes
Alright, I understand what the changes do now. Improves testing to only have to use one model and window instead of having to create multiples. It has also passed the auto test, so it's good to go.

2023-06-28 07:37 UTC, bakursait2 approved these changes
Those changes are good and helpful to remove the redundancy of creating instances from `Window` and `Model` classes.

2023-06-30 02:59 UTC, criticalglitch approved these changes

2023-06-30 03:25 UTC, merged