Speed down with test
WSUCEG-7140/Tempus_Fugit_Minecraft pull request #55
Opened 2023-06-26 20:34 UTC by w1158mxs

Decrease speed by clicking the arrow down, because users can increase the speed with the arrow up so they need to slow down without stopping. fix issue #51 - I face challenges in issue #48 so I redo it please ignore 48

2023-06-27 16:35 UTC, bakursait2 requested changes
It is a cool feature to increase/decrease the speed. However, would not be better if we change the speed keys from arrowUp and arrowDown to something that is more handy to the user?

I mean it might be hard for a player to leave the mouse just to hit increase(arrowUp)/decrease(arrowDown) bottons. Instead we can use some letters that is close to his fingers such as (for example) `q` for speedUp and `e` for speedDown.
or we can use the mouse wheel to increase/decrease the speed.

2023-06-27 18:24 UTC, xieWright approved these changes
Passed all the tests in the auto testing and the code looks fine to me. Also adding self to the pyproject.toml works.

2023-06-27 18:50 UTC, bakursait2 approved these changes

2023-06-27 19:09 UTC, Lurk390 approved these changes
I agree with Abu Bakur, speed-up and speed-down would be better as different keys to improve user experience, however, this would be future feature to implement. Good work.

2023-06-27 19:16 UTC, w1158mxs commented on tempus_fugit_minecraft/main.py
> +            self.speed_down()
I agree with your idea to make one hand on the mouse and the other on the keyboard, I will make it a new issue.

2023-06-30 03:07 UTC, criticalglitch approved these changes

2023-06-30 23:26 UTC, w1158mxs reviewed
Test should be changes because we did merge two files to one test file

2023-07-04 17:33 UTC, merged

2023-07-27 00:12 UTC, w1158mxs commented
Test passed
![speed_down_with_test_screenshot](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/assets/133145869/70005e41-ea1f-4aab-8a58-ce2470c8375c)
for others, all tests are automated