Speed down with test
WSUCEG-7140/Tempus_Fugit_Minecraft pull request #65
Opened 2023-07-06 17:07 UTC by w1158mxs

Finish issue #61 
Change control Keys Q for speed up and E for speed down with a test of the Q key, and change playing manual.

2023-07-07 00:29 UTC, bakursait2 commented
This update makes it more flexible than before. Thanks for the update.

However, there is minor problem we need to solve before merging. The issue is I merged my branch `pass-through-clouds_issue#57` to the master. Now the master is allowing the player to pass through the clouds, but it is not the case in this branch `speed_down_with_test`.

Solution: with the help I got from @criticalglitch , you need to **`rebase` your branch** to the latest version. This won't affect your code though.

I will point out where the changes need to be.

2023-07-07 00:39 UTC, bakursait2 requested changes
I could not make a comment on lines this branch has not touched.
But the changes I am talking about:
1. in `collide()`, specifically in lines 801-802:
`if tuple(op) not in self.model.world:`
    `continue`
2. added a nee function `is_it_cloud_coordinates()`

The solution is to `rebase` this branch so it gets all the updates from the `master`.

2023-07-07 01:11 UTC, criticalglitch requested changes
The changes here look good on their own. No complaints with this specifically.

However there is a regression in functionality I found while playing and we can no longer pass through clouds.

You'll want to make sure you rebase your changes on top of the latest version of `master`. You can do that by following these steps:
1. `git checkout master` -- Switches to master branch
1. `git pull origin` -- Pulls the latest code in the master branch
1. `git branch -d "speed_down_with_test"` -- Deletes the speed_down_with_test from your local machine
1. `git checkout -b "speed_down_with_test"` -- Creates a new branch called speed_down_with_test on your local machine
1. <Remake and Commit your changes, should be a single commit, you can view all the changes on github at this point to make it easier>
1. `git push --force origin "speed_down_with_test"` -- Forces github to use the new commit(s) you made for the branch

2023-07-07 15:55 UTC, Lurk390 approved these changes
Looks good to me. I definitely prefer pressing Q/E instead of up/down. After rebasing the branch as mentioned in other comments, it should be good to merge!

2023-07-07 19:32 UTC, xieWright requested changes
Looking at it, test should be for both speed up and speed down. Passes all the checks so no problems on that side.

2023-07-07 19:32 UTC, xieWright commented on tests/test_main.py
Looking at it, you tested the speedup, but not the speed down. In addition, I think you should change the test name to something like test_speed_Q_key since you changed it from up to Q.

2023-07-08 06:24 UTC, w1158mxs commented on tests/test_main.py
Thank you, updated now with Q and E key down test

2023-07-08 20:16 UTC, bakursait2 approved these changes

2023-07-08 20:18 UTC, bakursait2 commented
All the changes looks perfect now. Thanks for the updates.

2023-07-09 00:41 UTC, xieWright requested changes
Just minor naming nitpicks, but the function name should say exactly what the function does and thus remove the need for comments.

2023-07-09 00:41 UTC, xieWright commented on tempus_fugit_minecraft/window.py
In regards to the function name, you should be able to change the name such that you don't need the comment anymore.

2023-07-10 01:03 UTC, criticalglitch commented on tempus_fugit_minecraft/window.py
I wouldn't worry about it so much here. That will be fixed in the near future in an upcoming pull request.

2023-07-10 01:09 UTC, criticalglitch approved these changes
Looks good.

2023-07-10 22:31 UTC, xieWright approved these changes

2023-07-10 22:33 UTC, merged