Mark embedded doc
WSUCEG-7140/Tempus_Fugit_Minecraft pull request #94
Opened 2023-07-23 18:49 UTC by xieWright

Updated remaining Doxygen comments in Shaders, Lighting, and some in Window.

2023-07-24 01:01 UTC, criticalglitch approved these changes

2023-07-24 01:36 UTC, bakursait2 requested changes
- All editing looks perfect. However, I think we are missing:
  - [Issue#42](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/42) in `model.handle_secondary_action()`
  - [Issue#57](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/57) in `model.collide()`
  - [Issue#82](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/82) in `window.handle_flight()`
  - [Issue#22](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/22) in `window.on_mouse_press()`
  - [Issue#22](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/22) in `window.on_mouse_motion()`
  - change Issue number from [#38](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/38) to [Issue#37](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/37) in `player.speed_up()`
- We need a description for class `Block`. I thought I added it in my branch but apparently I forgot. Sorry for that.

Thanks for your effort.

2023-07-24 16:24 UTC, xieWright commented
Finished writing the comments for the missing functions in model. However, since world hasn't been merged yet, I can't do those yet.

2023-07-24 19:05 UTC, w1158mxs requested changes
Didn't pass test, Need to be fixed

2023-07-24 20:08 UTC, xieWright commented
Edited it back so that the tests would pass. However, I think handle_primary_action and handle_secondary_action should get a name change in the future to reflect that it's destroying and building blocks.

2023-07-25 05:43 UTC, w1158mxs commented
> * All editing looks perfect. However, I think we are missing:
>   
>   * [Issue#42](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/42) in `model.handle_secondary_action()`
>   * [Issue#57](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/57) in `model.collide()`
>   * [Issue#82](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/82) in `world.handle_flight()`
>   * [Issue#22](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/22) in `world.on_mouse_press()`
>   * [Issue#22](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/22) in `world.on_mouse_motion()`
>   * change Issue number from [#38](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/38) to [Issue#37](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/37) in `player.speed_up()`
> * We need a description for class `Block`. I thought I added it in my branch but apparently, I forgot. Sorry for that.
> 
> Thanks for your effort.

Never mind, I did them all!

2023-07-25 19:02 UTC, w1158mxs approved these changes

2023-07-25 19:02 UTC, w1158mxs commented on tempus_fugit_minecraft/window.py
> +            from the ingame time between 0-11 light decreases while from 12-23 light increases
in game

2023-07-25 19:12 UTC, Lurk390 requested changes
Looks good overall, just some formatting changes

2023-07-25 19:12 UTC, Lurk390 commented on tempus_fugit_minecraft/sound.py
> +#issue 17
This is redundant with the docstring in the init

2023-07-25 19:12 UTC, Lurk390 commented on tempus_fugit_minecraft/sound.py
> +        '''!Initializes the class Sound. If a file path is named, uses that to load the sound file
Keep `"""!` on a newline for readability

2023-07-25 19:12 UTC, Lurk390 commented on tempus_fugit_minecraft/sound.py
> +        '''!Loads the sound into the media player
Keep `"""!` on a newline for readability

2023-07-25 19:12 UTC, Lurk390 commented on tempus_fugit_minecraft/sound.py
> +        '''!Plays the sound file contained in the class
Keep `"""!` on a newline for readability

2023-07-25 19:12 UTC, Lurk390 commented on tempus_fugit_minecraft/sound.py
> +        '''!Initializes the class BackgroundSound. This is to separate sounds that will loop and have different
Keep `"""!` on a newline for readability

2023-07-26 14:06 UTC, bakursait2 requested changes
> Finished writing the comments for the missing functions in model. However, since world hasn't been merged yet, I can't do those yet.
Sorry, I made a mistake when I mentioned a change to `world.on_mouse_press()` because it is not there yet. I meant to make those changes on `window.on_mouse_press()`.

Also the above amend request has not been resolved. Here I am mention it:
- [Issue#57](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/57) in `model.collide()`
- [Issue#82](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/82) in `window.handle_flight()`
- [Issue#22](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/22) in `window.on_mouse_press()`
- [Issue#22](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/22) in `window.on_mouse_motion()`
- change Issue number from [#38](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/38) to [Issue#37] in `player.speed_up()`

I know this is not in your PR plan but I believe since you are adding comments and links on the same files that I want these updates to be added, then I believe that would be fine.

Thank you.

2023-07-26 14:42 UTC, bakursait2 approved these changes

2023-07-26 16:15 UTC, Lurk390 requested changes
Everything looks good to me, however, the tests are still saying they failed on my end.

2023-07-26 16:17 UTC, xieWright commented
Yeah, found a syntax error, fixed it.

2023-07-26 16:19 UTC, Lurk390 approved these changes

2023-07-26 16:20 UTC, merged